# Generated by Django 2.1 on 2020-02-13 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
