# Generated by Django 2.1 on 2020-02-27 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=250)),
                ('quote', models.CharField(max_length=300)),
                ('rate', models.IntegerField()),
                ('ratings', models.IntegerField()),
                ('i_will_show_you', models.TextField()),
                ('about_me', models.TextField()),
                ('laguages', models.CharField(max_length=250)),
                ('isAvailable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isActive', models.BooleanField(default=True)),
                ('location', models.CharField(max_length=250)),
                ('dateStart', models.DateField()),
                ('dateEnd', models.DateField()),
                ('price', models.IntegerField()),
                ('conversations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Conversations')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='isGuide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trips',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.User'),
        ),
        migrations.AddField(
            model_name='trips',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Guide'),
        ),
        migrations.AddField(
            model_name='trips',
            name='reviews',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Reviews'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='tripId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_requests_created', to='mainApp.Trips'),
        ),
        migrations.AddField(
            model_name='guide',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.User'),
        ),
        migrations.AddField(
            model_name='conversations',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.User'),
        ),
        migrations.AddField(
            model_name='conversations',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_requests_created', to='mainApp.User'),
        ),
        migrations.AddField(
            model_name='conversations',
            name='tripId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_requests_created', to='mainApp.Trips'),
        ),
    ]
