# Generated by Django 2.1 on 2020-03-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_auto_20200330_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='ratings',
            field=models.IntegerField(default=0),
        ),
    ]
