# Generated by Django 2.1 on 2020-03-30 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_auto_20200330_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversations',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='trip',
        ),
    ]
