# Generated by Django 2.1 on 2020-03-30 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_auto_20200330_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trips',
            name='conversations',
        ),
        migrations.AddField(
            model_name='conversations',
            name='trip',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='conversations_requests_created', to='mainApp.Trips'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
