# Generated by Django 2.1 on 2020-04-03 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_auto_20200403_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='reviews',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainApp.Reviews'),
        ),
    ]
